source:        .
destination:   ./_site
includes:      ./_includes

markdown:      kramdown
permalink:     /:title/

name:          Alexandra D'Sa
url:           http://alexandradsa.com
description:   Alexandra D'Sa — Actress and Performer
root_desc:     "Alexandra D'Sa — Actress and Performer"

exclude: ['README.markdown', 'config.rb']
include: ['.htaccess']

gems:
- jekyll-assets
- jekyll-sitemap
# This will require each of these gems automatically.

assets:
js_compressor: uglifier
css_compressor: sass
cache: true
cachebust: hard

sitemap:
file: "/sitemap.xml"
exclude:
- "/feed.xml"
include_posts:
- "/news/index.html"